{
 "title": "Plex Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Capacity Summary",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Used Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore_disk",
     "select": [
      [
       { "params": [ "used_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    },
    {
     "alias": "Free Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "SELECT mean(\"capacity_latest\") - mean(\"used_latest\") FROM \"vsphere_datastore_disk\" WHERE (\"source\" =~ /^$datastore$/) AND $timeFilter GROUP BY time($__interval), \"source\" fill(null)",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    }
   ]
  },
  {
   "title": "Plex Streams",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "active_streams",
     "select": [
      [
       { "params": [ "active_streams" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "All" }
     ]
    }
   ]
  },
  {
   "title": "Active Plex Streams",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "now_playing",
     "query": "SELECT last(\"stream_title\") AS Title, \"media_type\" AS \"Media Type\", \"resolution\" as Quality, \"player\" as Player, \"user\" as \"User\", \"host\" as \"Server\" FROM \"now_playing\" WHERE time > now() - 10s GROUP BY \"session_id\"",
     "select": [
      [
       { "params": [ "stream_title" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "player" ], "type": "field" }
      ],
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "plex1.ho.me" }
     ]
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "libraries",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "lib_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "libraries",
     "select": [
      [
       { "params": [ "items" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "lib_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "NZBs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM nzbs.mynzbs;"
    }
   ]
  },
  {
   "title": "WAN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "WAN1 Rcvd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "igb0" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "pfsense.chrisbergeron.com" }
     ]
    },
    {
     "alias": "WAN1 Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "igb0" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "pfsense.chrisbergeron.com" }
     ]
    }
   ]
  },
  {
   "title": "VPN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "PIAVPN Rcvd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ovpnc2" }
     ]
    },
    {
     "alias": "PIAVPN Sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "ovpnc2" }
     ]
    }
   ]
  },
  {
   "title": "Recent Downloads",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "select nzb AS Name,entry_date AS 'When' from mynzbs order by entry_date desc limit 5;",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "DNSMasq Cache",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "dnsmasq_hits", "legendFormat": "Hits" },
    { "expr": "dnsmasq_misses", "legendFormat": "Misses" }
   ]
  },
  {
   "title": "CPU Utilization Avg %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "CPU Utilization MHz" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "used_summation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 11 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "deckbytes", "label": "RAM Usage in GB" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Ready Avg %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "percent", "label": "% CPU Ready Avg." }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "select": [
      [
       { "params": [ "readiness_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Adapter Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "numberReadAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "numberWriteAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "KBps" }
   ],
   "targets": [
    {
     "alias": "Write - $tag_disk",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "read_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    },
    {
     "alias": "Read - $tag_disk",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_virtualDisk",
     "select": [
      [
       { "params": [ "write_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
     ]
    }
   ]
  }
 ]
}